### ISSUE TITLE
Load only the required properties

### ISSUE THREAD

**Issue by dkulyk** [IsraelOrtuno/Propertier#23]
If you want only specific values, then there is no sense in getting them all

``` php
Client::query()
->with('colors')
->get()->toArray();
====
array (
  'id' => 3,
  'colors' => 
  array (
    0 => 'SaddleBrown',
    1 => 'Bisque',
    2 => 'Moccasin',
  ),
)
```

If you load a specific field, then when exporting to the array you want to display only their(Only colors, but not the city...)

To reduce the query, you need to combine the fields in one relation in query scope.

**Comment by IsraelOrtuno** [comment]
I did not want to go this deep and would like to avoid using the Query Scope. EAV will be probably be used for giving some flexibility to the end-user but I do not thing this should be used in code as instead of doing this, if user knows a column will exist it will be probably be created in schema.

Thoughts?

**Comment by dkulyk** [comment]
If this reasoning, any field can be added to the table.
Not always all fields are required. but this functionality is not required, but would be less load database.

I offer the features that you do not have to sell. :)

**Comment by IsraelOrtuno** [comment]
Will leave it as a proposal now. Will consider as a future feature.
