### ISSUE TITLE
Stable version?

### ISSUE THREAD

**Issue by royduin** [IsraelOrtuno/Propertier#27]
@IsraelOrtuno thank you for your great work! I'd like to use it but is it production ready? Any plans for a stable release? And how to create a attribute isn't documented yet.

**Comment by IsraelOrtuno** [comment]
It is not ready yet, I want to have an stable version within the next month :)

**Comment by royduin** [comment]
I'm looking forward to the stable version! Maybe you can tell me the difference between Eavquent and https://cartalyst.com/manual/attributes/ ?

**Comment by IsraelOrtuno** [comment]
@royduin there are a few reasons I decided to code this package and not use that one instead:
1. Eavquent lets you store your datatypes independently instead of all on the same table as a `TEXT` type. It will store values in different value type tables: integers in `eav_values_integer` which `content` column will be `integer`. Same for any other datatype as varchar, datetime, serialized, etc... You could also create new datatypes by creating new models and just using Laravel mutators you could set how they are read and written.
2. Makes use of Eloquent relationships so we can easily query our models using attributes, check docs for this.
3. Let you have multivalued attributes. You could create an attribute which will store a collection of values, being automatically handled by Eavquent.
4. Includes attribute caching. 
5. Easy to extend and modify. Could easy be extended to create a new value type which will act as relation of entities. Lets imagine we would like to create a new `Contact` attribute labeled `manager` in our `Company` entity. This is already possible as the underlaying value is an Eloquent model.
6. Framework agnostic. Or at least I am going to try... However this is not a priority now.

Could say a few more, but I think it's enough :D

**Comment by royduin** [comment]
Thank you! I'm convinced and looking forward to the first stable release.

**Comment by IsraelOrtuno** [comment]
@royduin first release nearly ready, interested in beta testing?

Please drop me an email: ai.ortuno@gmail.com

**Comment by royduin** [comment]
Nice! I can just pull the latest version from the `master` branch?

**Comment by IsraelOrtuno** [comment]
Please email me so I will send you some directions for setting up now :D

Un saludo
Israel Ortuño

2016-04-04 18:39 GMT+02:00 Roy notifications@github.com:

**Comment by royduin** [comment]
You've got mail
